[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "thumbv7em-none-eabi",
]
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = []

[licenses]
allow = [
    "AGPL-3.0",
    "MIT",
]
confidence-threshold = 1.0
exceptions = []

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
